// src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { push, router } from 'svelte-spa-router';
  import { api } from '../../api/commands';
  import { downloads } from '../../stores/downloads.svelte';
  import { formatBytes } from '../../utils/format';
  import './Sidebar.css';

  interface NavItem {
    label: string;
    icon: string;
    filter: string | null;
    countSelector: 'all' | 'active' | 'paused' | 'completed';
  }

  const navItems: NavItem[] = [
    { label: 'All Downloads', icon: 'list', filter: null, countSelector: 'all' },
    { label: 'Active', icon: 'play_circle', filter: 'active', countSelector: 'active' },
    { label: 'Paused', icon: 'pause_circle', filter: 'paused', countSelector: 'paused' },
  ];

  const ACTIVE_ICON_STYLE = "font-variation-settings: 'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24";

  let diskSpace = $state<{ total: number; free: number } | null>(null);

  $effect(() => {
    async function loadDiskSpace() {
      try {
        diskSpace = await api.getDiskSpace();
      } catch {
        /* ignore */
      }
    }
    loadDiskSpace();
    const interval = setInterval(loadDiskSpace, 30000);
    return () => clearInterval(interval);
  });

  const currentFilter = $derived(
    router.location === '/' ? new URLSearchParams(router.querystring).get('filter') || null : '__settings__'
  );

  function getCount(selector: NavItem['countSelector']): number {
    switch (selector) {
      case 'all':
        return downloads.all.filter((d) => d.status !== 'complete').length;
      case 'active':
        return downloads.active.length;
      case 'paused':
        return downloads.paused.length;
      case 'completed':
        return downloads.completed.length;
    }
  }

  function handleNavClick(filter: string | null) {
    if (filter) {
      push(`/?filter=${filter}`);
    } else {
      push('/');
    }
  }

  const diskUsedPercent = $derived(
    diskSpace ? Math.round(((diskSpace.total - diskSpace.free) / diskSpace.total) * 100) : 0
  );
</script>

<aside class="sidebar">
  <div class="sidebar-inner">
    <!-- Header -->
    <div class="sidebar-header">
      <div class="logo">
        <div class="logo-icon-wrapper">
          <span class="material-symbols-outlined">bolt</span>
        </div>
        <div class="logo-info">
          <span class="logo-text">Gosh-Fetch</span>
          <span class="logo-subtitle">v2.0.6 &bull; Stable</span>
        </div>
      </div>
    </div>

    <!-- Navigation -->
    <nav class="sidebar-nav">
      {#each navItems as item (item.label)}
        {@const isActive = currentFilter === item.filter}
        {@const count = getCount(item.countSelector)}
        <button
          class="nav-item{isActive ? ' active' : ''}"
          onclick={() => handleNavClick(item.filter)}
        >
          <span
            class="material-symbols-outlined nav-icon"
            style={isActive ? ACTIVE_ICON_STYLE : undefined}
          >
            {item.icon}
          </span>
          <span class="nav-label">{item.label}</span>
          {#if count > 0}
            <span class="nav-badge{isActive ? ' active' : ''}">{count}</span>
          {/if}
        </button>
      {/each}

      <!-- History Link -->
      <button
        class="nav-item{router.location === '/history' ? ' active' : ''}"
        onclick={() => push('/history')}
      >
        <span
          class="material-symbols-outlined nav-icon"
          style={router.location === '/history' ? ACTIVE_ICON_STYLE : undefined}
        >
          history
        </span>
        <span class="nav-label">History</span>
        {#if downloads.completed.length > 0}
          <span class="nav-badge{router.location === '/history' ? ' active' : ''}"
            >{downloads.completed.length}</span
          >
        {/if}
      </button>

      <!-- Statistics Link -->
      <button
        class="nav-item{router.location === '/statistics' ? ' active' : ''}"
        onclick={() => push('/statistics')}
      >
        <span
          class="material-symbols-outlined nav-icon"
          style={router.location === '/statistics' ? ACTIVE_ICON_STYLE : undefined}
        >
          monitoring
        </span>
        <span class="nav-label">Statistics</span>
      </button>

      <!-- Mirror Link -->
      <button
        class="nav-item{router.location === '/mirror' ? ' active' : ''}"
        onclick={() => push('/mirror')}
      >
        <span
          class="material-symbols-outlined nav-icon"
          style={router.location === '/mirror' ? ACTIVE_ICON_STYLE : undefined}
        >
          folder_copy
        </span>
        <span class="nav-label">Mirror</span>
      </button>

      <!-- Scheduler Link -->
      <button
        class="nav-item{router.location === '/scheduler' ? ' active' : ''}"
        onclick={() => push('/scheduler')}
      >
        <span
          class="material-symbols-outlined nav-icon"
          style={router.location === '/scheduler' ? ACTIVE_ICON_STYLE : undefined}
        >
          calendar_month
        </span>
        <span class="nav-label">Scheduler</span>
      </button>
    </nav>

    <!-- Footer -->
    <div class="sidebar-footer">
      <!-- Storage Widget -->
      {#if diskSpace}
        <div class="storage-widget">
          <div class="storage-header">
            <span class="storage-label">Storage</span>
            <span class="storage-percent">{diskUsedPercent}%</span>
          </div>
          <div class="storage-bar">
            <div class="storage-bar-fill" style="width: {diskUsedPercent}%"></div>
          </div>
          <span class="storage-detail">
            {formatBytes(diskSpace.free)} free of {formatBytes(diskSpace.total)}
          </span>
        </div>
      {/if}

      <!-- Settings Link -->
      <button
        class="nav-item settings-link{router.location === '/settings' ? ' active' : ''}"
        onclick={() => push('/settings')}
      >
        <span class="material-symbols-outlined nav-icon">settings</span>
        <span class="nav-label">Settings</span>
      </button>
    </div>
  </div>
</aside>

// src/components/layout/Sidebar.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation, useSearchParams } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { selectDownloads, selectActiveDownloads, selectPausedDownloads, selectCompletedDownloads } from '../../store/downloadSlice';
import { formatBytes } from '../../lib/utils/format';
import './Sidebar.css';

interface NavItem {
  label: string;
  icon: string;
  filter: string | null;
  countSelector: 'all' | 'active' | 'paused' | 'completed';
}

const navItems: NavItem[] = [
  { label: 'All Downloads', icon: 'list', filter: null, countSelector: 'all' },
  { label: 'Active', icon: 'play_circle', filter: 'active', countSelector: 'active' },
  { label: 'Paused', icon: 'pause_circle', filter: 'paused', countSelector: 'paused' },
];

export default function Sidebar() {
  const navigate = useNavigate();
  const location = useLocation();
  const [searchParams] = useSearchParams();
  const allDownloads = useSelector(selectDownloads);
  const activeDownloads = useSelector(selectActiveDownloads);
  const pausedDownloads = useSelector(selectPausedDownloads);
  const completedDownloads = useSelector(selectCompletedDownloads);

  const [diskSpace, setDiskSpace] = useState<{ total: number; free: number } | null>(null);

  useEffect(() => {
    async function loadDiskSpace() {
      try {
        const space = await window.electronAPI.getDiskSpace();
        setDiskSpace(space);
      } catch { /* ignore */ }
    }
    loadDiskSpace();
    const interval = setInterval(loadDiskSpace, 30000);
    return () => clearInterval(interval);
  }, []);

  const currentFilter = location.pathname === '/' ? (searchParams.get('filter') || null) : '__settings__';

  function getCount(selector: NavItem['countSelector']): number {
    switch (selector) {
      case 'all': return allDownloads.filter(d => d.status !== 'complete').length;
      case 'active': return activeDownloads.length;
      case 'paused': return pausedDownloads.length;
      case 'completed': return completedDownloads.length;
    }
  }

  function handleNavClick(filter: string | null) {
    if (filter) {
      navigate(`/?filter=${filter}`);
    } else {
      navigate('/');
    }
  }

  const diskUsedPercent = diskSpace ? Math.round(((diskSpace.total - diskSpace.free) / diskSpace.total) * 100) : 0;

  return (
    <aside className="sidebar">
      <div className="sidebar-inner">
        {/* Header */}
        <div className="sidebar-header">
          <div className="logo">
            <div className="logo-icon-wrapper">
              <span className="material-symbols-outlined">bolt</span>
            </div>
            <div className="logo-info">
              <span className="logo-text">Gosh-Fetch</span>
              <span className="logo-subtitle">v2.0.3 &bull; Stable</span>
            </div>
          </div>
        </div>

        {/* Navigation */}
        <nav className="sidebar-nav">
          {navItems.map((item) => {
            const isActive = currentFilter === item.filter;
            const count = getCount(item.countSelector);
            return (
              <button
                key={item.label}
                className={`nav-item${isActive ? ' active' : ''}`}
                onClick={() => handleNavClick(item.filter)}
              >
                <span
                  className="material-symbols-outlined nav-icon"
                  style={isActive ? { fontVariationSettings: "'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24" } : undefined}
                >
                  {item.icon}
                </span>
                <span className="nav-label">{item.label}</span>
                {count > 0 && (
                  <span className={`nav-badge${isActive ? ' active' : ''}`}>{count}</span>
                )}
              </button>
            );
          })}

          {/* History Link */}
          <button
            className={`nav-item${location.pathname === '/history' ? ' active' : ''}`}
            onClick={() => navigate('/history')}
          >
            <span
              className="material-symbols-outlined nav-icon"
              style={location.pathname === '/history' ? { fontVariationSettings: "'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24" } : undefined}
            >
              history
            </span>
            <span className="nav-label">History</span>
            {completedDownloads.length > 0 && (
              <span className={`nav-badge${location.pathname === '/history' ? ' active' : ''}`}>{completedDownloads.length}</span>
            )}
          </button>

          {/* Statistics Link */}
          <button
            className={`nav-item${location.pathname === '/statistics' ? ' active' : ''}`}
            onClick={() => navigate('/statistics')}
          >
            <span
              className="material-symbols-outlined nav-icon"
              style={location.pathname === '/statistics' ? { fontVariationSettings: "'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24" } : undefined}
            >
              monitoring
            </span>
            <span className="nav-label">Statistics</span>
          </button>

          {/* Scheduler Link */}
          <button
            className={`nav-item${location.pathname === '/scheduler' ? ' active' : ''}`}
            onClick={() => navigate('/scheduler')}
          >
            <span
              className="material-symbols-outlined nav-icon"
              style={location.pathname === '/scheduler' ? { fontVariationSettings: "'FILL' 1, 'wght' 400, 'GRAD' 0, 'opsz' 24" } : undefined}
            >
              calendar_month
            </span>
            <span className="nav-label">Scheduler</span>
          </button>
        </nav>

        {/* Footer */}
        <div className="sidebar-footer">
          {/* Storage Widget */}
          {diskSpace && (
            <div className="storage-widget">
              <div className="storage-header">
                <span className="storage-label">Storage</span>
                <span className="storage-percent">{diskUsedPercent}%</span>
              </div>
              <div className="storage-bar">
                <div className="storage-bar-fill" style={{ width: `${diskUsedPercent}%` }} />
              </div>
              <span className="storage-detail">
                {formatBytes(diskSpace.free)} free of {formatBytes(diskSpace.total)}
              </span>
            </div>
          )}

          {/* Settings Link */}
          <button
            className={`nav-item settings-link${location.pathname === '/settings' ? ' active' : ''}`}
            onClick={() => navigate('/settings')}
          >
            <span className="material-symbols-outlined nav-icon">settings</span>
            <span className="nav-label">Settings</span>
          </button>
        </div>
      </div>
    </aside>
  );
}
