// src/routes/About.svelte
<script lang="ts">
  import { api } from '../lib/api/commands';
  import './About.css';

  const TECH_STACK = [
    { name: 'Svelte', icon: 'code', color: '#FF3E00' },
    { name: 'Tauri', icon: 'desktop_windows', color: '#FFC131' },
    { name: 'Rust', icon: 'settings_suggest', color: '#DEA584' },
    { name: 'SQLite', icon: 'storage', color: '#3e8eb5' },
  ];

  let appInfo = $state<any>(null);

  $effect(() => {
    api.getAppInfo().then((info) => (appInfo = info)).catch(console.error);
  });
</script>

{#if !appInfo}
  <div class="page"><div class="about-loading">Loading...</div></div>
{:else}
  <div class="page">
    <div class="about-page">
      <!-- Hero -->
      <div class="about-hero">
        <div class="about-icon-box">
          <div class="icon-hover-gradient"></div>
          <img src="/logo.png" alt="Gosh-Fetch" />
        </div>
        <h1 class="about-title">{appInfo.name}</h1>
        <span class="about-version-badge">v{appInfo.version} Stable</span>
      </div>

      <!-- Tech Stack -->
      <div class="about-stack-section">
        <h3 class="about-stack-label">Tech Stack</h3>
        <div class="about-stack-grid">
          {#each TECH_STACK as tech (tech.name)}
            <div class="about-stack-card">
              <span class="material-symbols-outlined stack-icon" style="color: {tech.color}">
                {tech.icon}
              </span>
              <span class="stack-name">{tech.name}</span>
            </div>
          {/each}
        </div>
      </div>

      <!-- Footer Links -->
      <div class="about-footer-links">
        <a class="about-footer-link" href={appInfo.repository} target="_blank" rel="noopener noreferrer">
          <span class="material-symbols-outlined">code</span>
          GitHub Repo
        </a>
        <a
          class="about-footer-link"
          href={`${appInfo.repository}/blob/main/LICENSE`}
          target="_blank"
          rel="noopener noreferrer"
        >
          <span class="material-symbols-outlined">gavel</span>
          AGPL-3.0
        </a>
        <a
          class="about-footer-link report"
          href={`${appInfo.repository}/issues/new`}
          target="_blank"
          rel="noopener noreferrer"
        >
          <span class="material-symbols-outlined">bug_report</span>
          Report Issue
        </a>
      </div>
    </div>
  </div>
{/if}

// src/pages/About.tsx
import React, { useEffect, useState } from 'react';
import { Shield, CheckCircle, Github, Zap, Lock, Download } from 'lucide-react';
import { api } from '../lib/api';
import './About.css';

export default function About() {
  const [appInfo, setAppInfo] = useState<any>(null);
  const [engineRunning, setEngineRunning] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const info = await api.getAppInfo();
        setAppInfo(info);
        const versionInfo = await api.getEngineVersion();
        setEngineRunning(versionInfo.running);
      } catch (e) {
        console.error('Failed to load app info:', e);
      }
    })();
  }, []);

  if (!appInfo) return <div className="page"><div className="loading">Loading...</div></div>;

  return (
    <div className="page">
      <header className="page-header"><h1>About</h1></header>
      <div className="about-content">
        {/* Hero */}
        <div className="app-hero">
          <div className="hero-icon-wrapper">
            <img src="/logo.png" alt="Gosh-Fetch" width={80} height={80} />
          </div>
          <h2>{appInfo.name}</h2>
          <span className="version-pill">v{appInfo.version}</span>
          <p className="app-description">{appInfo.description}</p>
        </div>

        {/* Engine */}
        <section className="about-card">
          <div className="about-card-header">
            <h3>Download Engine</h3>
            <span className={`status-indicator ${engineRunning ? 'connected' : 'disconnected'}`}>
              <span className="status-dot" />
              {engineRunning && <span className="status-ping" />}
              {engineRunning ? 'Connected' : 'Disconnected'}
            </span>
          </div>
          <div className="engine-grid">
            <div className="engine-detail">
              <span className="detail-label">Engine</span>
              <span className="detail-value">{appInfo.engine.name}</span>
            </div>
            <div className="engine-detail">
              <span className="detail-label">Version</span>
              <span className="detail-value">{appInfo.engine.version}</span>
            </div>
            <div className="engine-detail">
              <span className="detail-label">License</span>
              <span className="detail-value">{appInfo.engine.license}</span>
            </div>
            <div className="engine-detail">
              <span className="detail-label">Source</span>
              <a href={appInfo.engine.url} target="_blank" rel="noopener noreferrer" className="detail-value detail-link">GitHub</a>
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="about-card">
          <h3><Zap size={16} /> Features</h3>
          <div className="feature-chips">
            <span className="chip">HTTP/HTTPS</span>
            <span className="chip">BitTorrent</span>
            <span className="chip">Magnet URIs</span>
            <span className="chip">DHT</span>
            <span className="chip">PEX</span>
            <span className="chip">LPD</span>
            <span className="chip">Segmented Downloads</span>
            <span className="chip">Resume Support</span>
            <span className="chip">Native Rust</span>
          </div>
        </section>

        {/* Privacy */}
        <section className="about-card">
          <h3><Shield size={16} /> Privacy</h3>
          <p className="privacy-text">Gosh-Fetch respects your privacy. No telemetry, no analytics, no data collection. All data is stored locally on your device.</p>
          <div className="privacy-checks">
            <span className="privacy-check"><CheckCircle size={14} /> No telemetry or analytics</span>
            <span className="privacy-check"><CheckCircle size={14} /> No data collection</span>
            <span className="privacy-check"><CheckCircle size={14} /> No network activity unless initiated by you</span>
            <span className="privacy-check"><Lock size={14} /> Local Storage Only</span>
          </div>
        </section>

        {/* Footer */}
        <div className="about-footer">
          <p>Made with love and Rust</p>
          <a href={appInfo.repository} target="_blank" rel="noopener noreferrer" className="btn btn-secondary btn-sm">
            <Github size={14} /> View on GitHub
          </a>
        </div>
      </div>
    </div>
  );
}
