// src/lib/pages/Downloads.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import DownloadCard from '../components/downloads/DownloadCard.svelte';
  import AddDownloadModal from '../components/downloads/AddDownloadModal.svelte';
  import {
    getDownloads,
    getActiveDownloads,
    getPausedDownloads,
    getErrorDownloads,
    startPolling,
    stopPolling,
    pauseAll,
    resumeAll,
  } from '../stores/downloads.svelte';
  import { getStats } from '../stores/stats.svelte';
  import { formatSpeed } from '../utils/format';

  let showAddModal = $state(false);
  let filter = $state<'all' | 'active' | 'paused' | 'error'>('all');

  const allDownloads = $derived(getDownloads());
  const activeDownloads = $derived(getActiveDownloads());
  const pausedDownloads = $derived(getPausedDownloads());
  const errorDownloads = $derived(getErrorDownloads());
  const stats = $derived(getStats());

  const filteredDownloads = $derived(() => {
    const downloads = allDownloads.filter(d => d.status !== 'complete');
    switch (filter) {
      case 'active':
        return downloads.filter(d => d.status === 'active' || d.status === 'waiting');
      case 'paused':
        return downloads.filter(d => d.status === 'paused');
      case 'error':
        return downloads.filter(d => d.status === 'error');
      default:
        return downloads;
    }
  });

  onMount(() => {
    startPolling();
  });

  onDestroy(() => {
    stopPolling();
  });

  async function handlePauseAll() {
    await pauseAll();
  }

  async function handleResumeAll() {
    await resumeAll();
  }
</script>

<div class="page">
  <header class="page-header">
    <div class="header-left">
      <h1>Downloads</h1>
      <div class="header-stats">
        <span class="stat">
          <span class="stat-icon">↓</span>
          {formatSpeed(stats.downloadSpeed)}
        </span>
        <span class="stat">
          <span class="stat-icon">↑</span>
          {formatSpeed(stats.uploadSpeed)}
        </span>
        <span class="stat-divider">|</span>
        <span class="stat">{stats.numActive} active</span>
      </div>
    </div>

    <div class="header-actions">
      <button class="btn btn-secondary btn-sm" onclick={handlePauseAll}>
        ⏸ Pause All
      </button>
      <button class="btn btn-secondary btn-sm" onclick={handleResumeAll}>
        ▶ Resume All
      </button>
      <button class="btn btn-primary" onclick={() => (showAddModal = true)}>
        + Add Download
      </button>
    </div>
  </header>

  <div class="filter-bar">
    <button
      class="filter-btn"
      class:active={filter === 'all'}
      onclick={() => (filter = 'all')}
    >
      All
    </button>
    <button
      class="filter-btn"
      class:active={filter === 'active'}
      onclick={() => (filter = 'active')}
    >
      Active ({activeDownloads.length})
    </button>
    <button
      class="filter-btn"
      class:active={filter === 'paused'}
      onclick={() => (filter = 'paused')}
    >
      Paused ({pausedDownloads.length})
    </button>
    <button
      class="filter-btn"
      class:active={filter === 'error'}
      onclick={() => (filter = 'error')}
    >
      Errors ({errorDownloads.length})
    </button>
  </div>

  <div class="downloads-list">
    {#if filteredDownloads().length === 0}
      <div class="empty-state">
        <div class="empty-icon">📥</div>
        <h3>No downloads</h3>
        <p>Click "Add Download" to get started</p>
      </div>
    {:else}
      {#each filteredDownloads() as download (download.gid)}
        <DownloadCard {download} />
      {/each}
    {/if}
  </div>
</div>

{#if showAddModal}
  <AddDownloadModal onClose={() => (showAddModal = false)} />
{/if}

<style>
  .page {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }

  .page-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: var(--space-lg);
    border-bottom: 1px solid var(--border-primary);
    background: var(--bg-secondary);
  }

  .header-left {
    display: flex;
    flex-direction: column;
    gap: var(--space-xs);
  }

  .header-left h1 {
    font-size: 20px;
    margin: 0;
  }

  .header-stats {
    display: flex;
    align-items: center;
    gap: var(--space-md);
    font-size: 12px;
    color: var(--text-muted);
  }

  .stat {
    display: flex;
    align-items: center;
    gap: var(--space-xs);
  }

  .stat-icon {
    color: var(--color-primary);
  }

  .stat-divider {
    color: var(--border-primary);
  }

  .header-actions {
    display: flex;
    gap: var(--space-sm);
  }

  .filter-bar {
    display: flex;
    gap: var(--space-xs);
    padding: var(--space-md) var(--space-lg);
    background: var(--bg-primary);
    border-bottom: 1px solid var(--border-secondary);
  }

  .filter-btn {
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-md);
    font-size: 13px;
    color: var(--text-secondary);
    transition: all var(--transition-fast);
  }

  .filter-btn:hover {
    background: var(--bg-hover);
    color: var(--text-primary);
  }

  .filter-btn.active {
    background: var(--bg-tertiary);
    color: var(--text-primary);
  }

  .downloads-list {
    flex: 1;
    overflow-y: auto;
    padding: var(--space-lg);
    display: flex;
    flex-direction: column;
    gap: var(--space-md);
  }

  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: var(--space-2xl);
    text-align: center;
  }

  .empty-icon {
    font-size: 48px;
    margin-bottom: var(--space-md);
    opacity: 0.5;
  }

  .empty-state h3 {
    font-size: 18px;
    margin-bottom: var(--space-sm);
    color: var(--text-primary);
  }

  .empty-state p {
    color: var(--text-muted);
  }
</style>

// src/pages/Downloads.tsx
import React, { useEffect, useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import DownloadCard from '../components/downloads/DownloadCard';
import AddDownloadModal from '../components/downloads/AddDownloadModal';
import {
  selectDownloads,
  selectActiveDownloads,
  selectPausedDownloads,
  selectErrorDownloads,
  fetchDownloads,
  loadCompletedHistory,
  restoreIncomplete,
  pauseAll,
  resumeAll,
  pauseDownload,
  resumeDownload,
  removeDownload,
} from '../store/downloadSlice';
import { selectStats } from '../store/statsSlice';
import { formatSpeed } from '../lib/utils/format';
import type { AppDispatch } from '../store/store';
import './Downloads.css';

export default function Downloads() {
  const dispatch = useDispatch<AppDispatch>();
  const allDownloads = useSelector(selectDownloads);
  const activeDownloads = useSelector(selectActiveDownloads);
  const pausedDownloads = useSelector(selectPausedDownloads);
  const errorDownloads = useSelector(selectErrorDownloads);
  const stats = useSelector(selectStats);
  const [showAddModal, setShowAddModal] = useState(false);
  const [filter, setFilter] = useState<'all' | 'active' | 'paused' | 'error'>('all');
  const [selectedGids, setSelectedGids] = useState<Set<string>>(new Set());

  useEffect(() => {
    dispatch(loadCompletedHistory());
    dispatch(restoreIncomplete());
    dispatch(fetchDownloads());
    const interval = setInterval(() => dispatch(fetchDownloads()), 1000);
    return () => clearInterval(interval);
  }, [dispatch]);

  const filteredDownloads = allDownloads.filter(d => d.status !== 'complete').filter(d => {
    switch (filter) {
      case 'active': return d.status === 'active' || d.status === 'waiting';
      case 'paused': return d.status === 'paused';
      case 'error': return d.status === 'error';
      default: return true;
    }
  });

  const hasSelection = selectedGids.size > 0;
  const allSelected = filteredDownloads.length > 0 && filteredDownloads.every(d => selectedGids.has(d.gid));

  function handleSelect(gid: string, selected: boolean) {
    setSelectedGids(prev => {
      const next = new Set(prev);
      if (selected) next.add(gid);
      else next.delete(gid);
      return next;
    });
  }

  function handleSelectAll() {
    if (allSelected) {
      setSelectedGids(new Set());
    } else {
      setSelectedGids(new Set(filteredDownloads.map(d => d.gid)));
    }
  }

  async function handleBatchPause() {
    for (const gid of selectedGids) {
      try { await dispatch(pauseDownload(gid)); } catch { /* ignore */ }
    }
    setSelectedGids(new Set());
  }

  async function handleBatchResume() {
    for (const gid of selectedGids) {
      try { await dispatch(resumeDownload(gid)); } catch { /* ignore */ }
    }
    setSelectedGids(new Set());
  }

  async function handleBatchRemove() {
    for (const gid of selectedGids) {
      try { await dispatch(removeDownload({ gid, deleteFiles: false })); } catch { /* ignore */ }
    }
    setSelectedGids(new Set());
  }

  return (
    <div className="page">
      <header className="page-header">
        <div className="header-left">
          <h1>Downloads</h1>
          <div className="header-stats">
            <span className="stat"><span className="stat-icon">{'\u2193'}</span> {formatSpeed(stats.downloadSpeed)}</span>
            <span className="stat"><span className="stat-icon">{'\u2191'}</span> {formatSpeed(stats.uploadSpeed)}</span>
            <span className="stat-divider">|</span>
            <span className="stat">{stats.numActive} active</span>
          </div>
        </div>
        <div className="header-actions">
          <button className="btn btn-secondary btn-sm" onClick={() => dispatch(pauseAll())}>{'\u23F8'} Pause All</button>
          <button className="btn btn-secondary btn-sm" onClick={() => dispatch(resumeAll())}>{'\u25B6'} Resume All</button>
          <button className="btn btn-primary" onClick={() => setShowAddModal(true)}>+ Add Download</button>
        </div>
      </header>

      <div className="filter-bar">
        <label className="select-all-checkbox">
          <input type="checkbox" checked={allSelected} onChange={handleSelectAll} disabled={filteredDownloads.length === 0} />
        </label>
        <button className={`filter-btn${filter === 'all' ? ' active' : ''}`} onClick={() => setFilter('all')}>All</button>
        <button className={`filter-btn${filter === 'active' ? ' active' : ''}`} onClick={() => setFilter('active')}>Active ({activeDownloads.length})</button>
        <button className={`filter-btn${filter === 'paused' ? ' active' : ''}`} onClick={() => setFilter('paused')}>Paused ({pausedDownloads.length})</button>
        <button className={`filter-btn${filter === 'error' ? ' active' : ''}`} onClick={() => setFilter('error')}>Errors ({errorDownloads.length})</button>
      </div>

      {hasSelection && (
        <div className="batch-action-bar">
          <span className="batch-count">{selectedGids.size} selected</span>
          <button className="btn btn-secondary btn-sm" onClick={handleBatchPause}>{'\u23F8'} Pause</button>
          <button className="btn btn-secondary btn-sm" onClick={handleBatchResume}>{'\u25B6'} Resume</button>
          <button className="btn btn-destructive btn-sm" onClick={handleBatchRemove}>{'\uD83D\uDDD1'} Remove</button>
          <button className="btn btn-ghost btn-sm" onClick={() => setSelectedGids(new Set())}>Clear</button>
        </div>
      )}

      <div className="downloads-list">
        {filteredDownloads.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">{'\uD83D\uDCE5'}</div>
            <h3>No downloads</h3>
            <p>Click &quot;Add Download&quot; to get started</p>
          </div>
        ) : (
          filteredDownloads.map(download => (
            <DownloadCard
              key={download.gid}
              download={download}
              selected={selectedGids.has(download.gid)}
              onSelect={handleSelect}
            />
          ))
        )}
      </div>

      {showAddModal && <AddDownloadModal onClose={() => setShowAddModal(false)} />}
    </div>
  );
}
