// src/routes/Downloads.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { router } from 'svelte-spa-router';
  import { SvelteSet } from 'svelte/reactivity';
  import DownloadCard from '../lib/components/downloads/DownloadCard.svelte';
  import SortableList from '../lib/components/downloads/SortableList.svelte';
  import CompactDownloadRow from '../lib/components/downloads/CompactDownloadRow.svelte';
  import AddDownloadModal from '../lib/components/downloads/AddDownloadModal.svelte';
  import NotificationDropdown from '../lib/components/layout/NotificationDropdown.svelte';
  import { downloads } from '../lib/stores/downloads.svelte';
  import { ui } from '../lib/stores/ui.svelte';
  import { getFileExtension } from '../lib/utils/format';
  import type { Download } from '../lib/types/download';
  import './Downloads.css';

  type FileCategory = 'all' | 'video' | 'audio' | 'documents' | 'software' | 'images';

  const CATEGORIES: { label: string; value: FileCategory }[] = [
    { label: 'All Files', value: 'all' },
    { label: 'Video', value: 'video' },
    { label: 'Audio', value: 'audio' },
    { label: 'Documents', value: 'documents' },
    { label: 'Software', value: 'software' },
    { label: 'Images', value: 'images' },
  ];

  function getFileCategory(download: Download): FileCategory {
    const ext = getFileExtension(download.name);
    if (['mp4', 'mkv', 'avi', 'mov', 'wmv', 'flv', 'webm', 'm4v'].includes(ext)) return 'video';
    if (['mp3', 'flac', 'wav', 'aac', 'ogg', 'wma', 'm4a', 'opus'].includes(ext)) return 'audio';
    if (['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'rtf', 'odt', 'epub'].includes(ext)) return 'documents';
    if (['exe', 'msi', 'dmg', 'pkg', 'deb', 'rpm', 'appimage', 'snap', 'flatpak', 'apk', 'iso'].includes(ext)) return 'software';
    if (['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'ico', 'tiff', 'psd', 'raw'].includes(ext)) return 'images';
    if (['zip', 'tar', 'gz', 'bz2', 'xz', '7z', 'rar', 'zst'].includes(ext)) return 'software';
    if (download.downloadType === 'torrent' || download.downloadType === 'magnet') return 'software';
    return 'all';
  }

  let filter = $derived(
    (new URLSearchParams(router.querystring ?? '').get('filter') || 'all') as
      | 'all'
      | 'active'
      | 'paused'
      | 'completed'
  );

  let searchQuery = $state('');
  let category = $state<FileCategory>('all');
  const selectedGids = new SvelteSet<string>();
  let searchInputEl = $state<HTMLInputElement | null>(null);

  // Initial load + 5s polling
  $effect(() => {
    void downloads.loadCompletedHistory();
    void downloads.fetchDownloads();
    const interval = setInterval(() => void downloads.fetchDownloads(), 5000);
    return () => clearInterval(interval);
  });

  // Focus search signal (replaces 'gosh-fetch:focus-search')
  $effect(() => {
    const tick = ui.focusSearchTick;
    if (tick === 0) return;
    searchInputEl?.focus();
  });

  // Select-all signal (replaces 'gosh-fetch:select-all')
  $effect(() => {
    const tick = ui.selectAllTick;
    if (tick === 0) return;
    untrack(() => {
      selectedGids.clear();
      for (const d of allItems) selectedGids.add(d.gid);
    });
  });

  // Filter by status (from sidebar)
  let statusFiltered = $derived.by(() => {
    switch (filter) {
      case 'active': return downloads.active;
      case 'paused': return [...downloads.paused, ...downloads.errored];
      case 'completed': return downloads.completed;
      default: return [...downloads.all.filter((d) => d.status !== 'complete'), ...downloads.completed];
    }
  });

  // Filter by search query
  let searchFiltered = $derived.by(() => {
    if (!searchQuery.trim()) return statusFiltered;
    const q = searchQuery.toLowerCase();
    return statusFiltered.filter(
      (d) => d.name.toLowerCase().includes(q) || (d.url && d.url.toLowerCase().includes(q))
    );
  });

  // Filter by file category
  let categoryFiltered = $derived.by(() => {
    if (category === 'all') return searchFiltered;
    return searchFiltered.filter((d) => getFileCategory(d) === category);
  });

  // Split into active and paused/completed sections
  let activeItems = $derived(
    categoryFiltered.filter((d) => d.status === 'active' || d.status === 'waiting')
  );

  let pausedCompletedItems = $derived(
    categoryFiltered.filter((d) => d.status !== 'active' && d.status !== 'waiting')
  );

  // Sort active items by gidOrder
  let sortedActiveItems = $derived.by(() => {
    const orderMap = new Map(downloads.gidOrder.map((gid, i) => [gid, i]));
    return [...activeItems].sort((a, b) => {
      const ai = orderMap.get(a.gid) ?? Infinity;
      const bi = orderMap.get(b.gid) ?? Infinity;
      return ai - bi;
    });
  });

  let allItems = $derived([...sortedActiveItems, ...pausedCompletedItems]);
  let hasSelection = $derived(selectedGids.size > 0);
  let allSelected = $derived(allItems.length > 0 && allItems.every((d) => selectedGids.has(d.gid)));

  function handleSelect(gid: string, selected: boolean) {
    if (selected) selectedGids.add(gid);
    else selectedGids.delete(gid);
  }

  function handleSelectAll() {
    if (allSelected) {
      selectedGids.clear();
    } else {
      selectedGids.clear();
      for (const d of allItems) selectedGids.add(d.gid);
    }
  }

  async function handleBatchPause() {
    for (const gid of selectedGids) {
      try { await downloads.pause(gid); } catch { /* ignore */ }
    }
    selectedGids.clear();
  }

  async function handleBatchResume() {
    for (const gid of selectedGids) {
      try { await downloads.resume(gid); } catch { /* ignore */ }
    }
    selectedGids.clear();
  }

  async function handleBatchRemove() {
    for (const gid of [...selectedGids]) {
      try { await downloads.remove(gid); } catch { /* ignore */ }
    }
    selectedGids.clear();
  }

  let totalItems = $derived(categoryFiltered.length);
  let showEmptyState = $derived(
    !downloads.isLoading && totalItems === 0 && !searchQuery && category === 'all'
  );
  let showNoResults = $derived(
    !downloads.isLoading && totalItems === 0 && (searchQuery !== '' || category !== 'all')
  );
</script>

<div class="page">
  <header class="toolbar-header">
    <div class="search-bar">
      <span class="material-symbols-outlined">search</span>
      <input
        bind:this={searchInputEl}
        class="search-input"
        type="text"
        placeholder="Search by filename or paste URL..."
        bind:value={searchQuery}
      />
      <kbd class="search-shortcut">Ctrl K</kbd>
    </div>
    <div class="toolbar-actions">
      <NotificationDropdown />
      <button class="btn btn-primary" onclick={() => ui.openAddModal()}>
        <span class="material-symbols-outlined" style="font-size: 20px">add</span>
        Add Download
      </button>
    </div>
  </header>

  {#if hasSelection}
    <div class="batch-action-bar">
      <label class="select-all-checkbox">
        <input type="checkbox" checked={allSelected} onchange={handleSelectAll} aria-label="Select all downloads" />
      </label>
      <span class="batch-count">{selectedGids.size} selected</span>
      <button class="btn btn-secondary btn-sm" onclick={handleBatchPause}>
        <span class="material-symbols-outlined" style="font-size: 14px">pause</span> Pause
      </button>
      <button class="btn btn-secondary btn-sm" onclick={handleBatchResume}>
        <span class="material-symbols-outlined" style="font-size: 14px">play_arrow</span> Resume
      </button>
      <button class="btn btn-destructive btn-sm" onclick={handleBatchRemove}>
        <span class="material-symbols-outlined" style="font-size: 14px">delete</span> Remove
      </button>
      <button class="btn btn-ghost btn-sm" onclick={() => selectedGids.clear()}>Clear</button>
    </div>
  {/if}

  {#if downloads.error}
    <div class="error-banner">
      <span class="material-symbols-outlined" style="font-size: 14px">error</span>
      <span>{downloads.error}</span>
      <button class="btn btn-ghost btn-sm" onclick={() => void downloads.fetchDownloads()}>Retry</button>
    </div>
  {/if}

  <div class="content-scroll">
    <!-- Category pills -->
    <div class="category-pills">
      {#each CATEGORIES as cat (cat.value)}
        <button
          class={`category-pill${category === cat.value ? ' active' : ''}`}
          onclick={() => (category = cat.value)}
        >
          {cat.label}
        </button>
      {/each}
    </div>

    {#if downloads.isLoading && totalItems === 0 && !searchQuery}
      <div class="empty-state">
        <span class="material-symbols-outlined spin" style="font-size: 32px">progress_activity</span>
        <p>Loading downloads...</p>
      </div>
    {:else if showEmptyState}
      <div class="empty-state">
        <div class="empty-icon">
          <span class="material-symbols-outlined" style="font-size: 48px">inbox</span>
        </div>
        <h3>No downloads</h3>
        <p>Click "Add Download" or press Ctrl+N to get started</p>
        <button class="btn btn-primary" onclick={() => ui.openAddModal()} style="margin-top: var(--space-md)">
          <span class="material-symbols-outlined" style="font-size: 14px">add</span> Add Download
        </button>
      </div>
    {:else if showNoResults}
      <div class="empty-state">
        <div class="empty-icon">
          <span class="material-symbols-outlined" style="font-size: 48px">search_off</span>
        </div>
        <h3>No results</h3>
        <p>Try a different search term or category</p>
      </div>
    {:else}
      <!-- Active Downloads Section -->
      {#if sortedActiveItems.length > 0}
        <div class="download-section">
          <div class="dl-section-header">
            <span class="section-dot green"></span>
            <span class="section-label">Active Downloads</span>
          </div>
          <div class="downloads-list">
            <SortableList items={sortedActiveItems}>
              {#snippet renderItem(download: Download)}
                <DownloadCard
                  {download}
                  selected={selectedGids.has(download.gid)}
                  onSelect={handleSelect}
                />
              {/snippet}
            </SortableList>
            <div class="add-more-zone" onclick={() => ui.openAddModal()}>
              <span class="material-symbols-outlined" style="font-size: 16px">add</span>
              <span>Ready for more</span>
            </div>
          </div>
        </div>
      {/if}

      <!-- Paused & Recent Section -->
      {#if pausedCompletedItems.length > 0}
        <div class="download-section">
          <div class="dl-section-header">
            <span class="section-dot yellow"></span>
            <span class="section-label">Paused &amp; Recent</span>
          </div>
          <div class="compact-list">
            {#each pausedCompletedItems as download (download.gid)}
              <CompactDownloadRow
                {download}
                selected={selectedGids.has(download.gid)}
                onSelect={handleSelect}
              />
            {/each}
          </div>
        </div>
      {/if}

      <!-- If only active but no paused, still show add zone -->
      {#if sortedActiveItems.length === 0 && pausedCompletedItems.length > 0}
        <div class="add-more-zone" onclick={() => ui.openAddModal()}>
          <span class="material-symbols-outlined" style="font-size: 16px">add</span>
          <span>Ready for more</span>
        </div>
      {/if}
    {/if}
  </div>

  {#if ui.addModalOpen}
    <AddDownloadModal />
  {/if}
</div>

// src/pages/Downloads.tsx
import React, { useEffect, useState, useMemo, useRef } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { useSearchParams } from 'react-router-dom';
import {
  DndContext,
  DragOverlay,
  PointerSensor,
  KeyboardSensor,
  useSensor,
  useSensors,
  closestCenter,
  type DragStartEvent,
  type DragEndEvent,
} from '@dnd-kit/core';
import {
  SortableContext,
  verticalListSortingStrategy,
  arrayMove,
} from '@dnd-kit/sortable';
import DownloadCard from '../components/downloads/DownloadCard';
import SortableDownloadCard from '../components/downloads/SortableDownloadCard';
import CompactDownloadRow from '../components/downloads/CompactDownloadRow';
import AddDownloadModal from '../components/downloads/AddDownloadModal';
import NotificationDropdown from '../components/layout/NotificationDropdown';
import {
  selectDownloads,
  selectActiveDownloads,
  selectPausedDownloads,
  selectErrorDownloads,
  selectCompletedDownloads,
  fetchDownloads,
  loadCompletedHistory,
  pauseDownload,
  resumeDownload,
  removeDownload,
  syncPriorities,
  selectIsLoading,
  selectError,
} from '../store/downloadSlice';
import { selectGidOrder, setOrder, setDragging } from '../store/orderSlice';
import { getFileExtension } from '../lib/utils/format';
import type { Download } from '../lib/types/download';
import type { AppDispatch } from '../store/store';
import './Downloads.css';

type FileCategory = 'all' | 'video' | 'audio' | 'documents' | 'software' | 'images';

const CATEGORIES: { label: string; value: FileCategory }[] = [
  { label: 'All Files', value: 'all' },
  { label: 'Video', value: 'video' },
  { label: 'Audio', value: 'audio' },
  { label: 'Documents', value: 'documents' },
  { label: 'Software', value: 'software' },
  { label: 'Images', value: 'images' },
];

function getFileCategory(download: Download): FileCategory {
  const ext = getFileExtension(download.name);
  if (['mp4', 'mkv', 'avi', 'mov', 'wmv', 'flv', 'webm', 'm4v'].includes(ext)) return 'video';
  if (['mp3', 'flac', 'wav', 'aac', 'ogg', 'wma', 'm4a', 'opus'].includes(ext)) return 'audio';
  if (['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'rtf', 'odt', 'epub'].includes(ext)) return 'documents';
  if (['exe', 'msi', 'dmg', 'pkg', 'deb', 'rpm', 'appimage', 'snap', 'flatpak', 'apk', 'iso'].includes(ext)) return 'software';
  if (['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'ico', 'tiff', 'psd', 'raw'].includes(ext)) return 'images';
  if (['zip', 'tar', 'gz', 'bz2', 'xz', '7z', 'rar', 'zst'].includes(ext)) return 'software';
  if (download.downloadType === 'torrent' || download.downloadType === 'magnet') return 'software';
  return 'all';
}

export default function Downloads() {
  const dispatch = useDispatch<AppDispatch>();
  const [searchParams] = useSearchParams();
  const filter = (searchParams.get('filter') || 'all') as 'all' | 'active' | 'paused' | 'completed';
  const allDownloads = useSelector(selectDownloads);
  const activeDownloads = useSelector(selectActiveDownloads);
  const pausedDownloads = useSelector(selectPausedDownloads);
  const errorDownloads = useSelector(selectErrorDownloads);
  const completedDownloads = useSelector(selectCompletedDownloads);
  const isLoading = useSelector(selectIsLoading);
  const error = useSelector(selectError);
  const gidOrder = useSelector(selectGidOrder);
  const [showAddModal, setShowAddModal] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [category, setCategory] = useState<FileCategory>('all');
  const [selectedGids, setSelectedGids] = useState<Set<string>>(new Set());
  const [activeId, setActiveId] = useState<string | null>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
    useSensor(KeyboardSensor)
  );

  useEffect(() => {
    dispatch(loadCompletedHistory());
    dispatch(fetchDownloads());
    const interval = setInterval(() => dispatch(fetchDownloads()), 5000);

    const onOpenModal = () => setShowAddModal(true);
    const onFocusSearch = () => searchInputRef.current?.focus();
    window.addEventListener('gosh-fetch:open-add-modal', onOpenModal);
    window.addEventListener('gosh-fetch:focus-search', onFocusSearch);

    return () => {
      clearInterval(interval);
      window.removeEventListener('gosh-fetch:open-add-modal', onOpenModal);
      window.removeEventListener('gosh-fetch:focus-search', onFocusSearch);
    };
  }, [dispatch]);

  // Filter by status (from sidebar)
  const statusFiltered = useMemo(() => {
    switch (filter) {
      case 'active': return activeDownloads;
      case 'paused': return [...pausedDownloads, ...errorDownloads];
      case 'completed': return completedDownloads;
      default: return [...allDownloads.filter(d => d.status !== 'complete'), ...completedDownloads];
    }
  }, [filter, allDownloads, activeDownloads, pausedDownloads, errorDownloads, completedDownloads]);

  // Filter by search query
  const searchFiltered = useMemo(() => {
    if (!searchQuery.trim()) return statusFiltered;
    const q = searchQuery.toLowerCase();
    return statusFiltered.filter(d =>
      d.name.toLowerCase().includes(q) ||
      (d.url && d.url.toLowerCase().includes(q))
    );
  }, [statusFiltered, searchQuery]);

  // Filter by file category
  const categoryFiltered = useMemo(() => {
    if (category === 'all') return searchFiltered;
    return searchFiltered.filter(d => getFileCategory(d) === category);
  }, [searchFiltered, category]);

  // Split into active and paused/completed sections
  const activeItems = useMemo(() =>
    categoryFiltered.filter(d => d.status === 'active' || d.status === 'waiting'),
    [categoryFiltered]
  );

  const pausedCompletedItems = useMemo(() =>
    categoryFiltered.filter(d => d.status !== 'active' && d.status !== 'waiting'),
    [categoryFiltered]
  );

  // Sort active items by gidOrder
  const sortedActiveItems = useMemo(() => {
    const orderMap = new Map(gidOrder.map((gid, i) => [gid, i]));
    return [...activeItems].sort((a, b) => {
      const ai = orderMap.get(a.gid) ?? Infinity;
      const bi = orderMap.get(b.gid) ?? Infinity;
      return ai - bi;
    });
  }, [activeItems, gidOrder]);

  const activeDownload = activeId ? allDownloads.find(d => d.gid === activeId) : null;

  const allItems = [...sortedActiveItems, ...pausedCompletedItems];
  const hasSelection = selectedGids.size > 0;
  const allSelected = allItems.length > 0 && allItems.every(d => selectedGids.has(d.gid));

  function handleSelect(gid: string, selected: boolean) {
    setSelectedGids(prev => {
      const next = new Set(prev);
      if (selected) next.add(gid);
      else next.delete(gid);
      return next;
    });
  }

  function handleSelectAll() {
    if (allSelected) {
      setSelectedGids(new Set());
    } else {
      setSelectedGids(new Set(allItems.map(d => d.gid)));
    }
  }

  async function handleBatchPause() {
    for (const gid of selectedGids) {
      try { await dispatch(pauseDownload(gid)); } catch { /* ignore */ }
    }
    setSelectedGids(new Set());
  }

  async function handleBatchResume() {
    for (const gid of selectedGids) {
      try { await dispatch(resumeDownload(gid)); } catch { /* ignore */ }
    }
    setSelectedGids(new Set());
  }

  async function handleBatchRemove() {
    for (const gid of selectedGids) {
      try { await dispatch(removeDownload({ gid, deleteFiles: false })); } catch { /* ignore */ }
    }
    setSelectedGids(new Set());
  }

  function handleDragStart(event: DragStartEvent) {
    setActiveId(event.active.id as string);
    dispatch(setDragging(true));
  }

  function handleDragEnd(event: DragEndEvent) {
    const { active, over } = event;
    setActiveId(null);
    dispatch(setDragging(false));

    if (over && active.id !== over.id) {
      const oldIndex = gidOrder.indexOf(active.id as string);
      const newIndex = gidOrder.indexOf(over.id as string);
      if (oldIndex !== -1 && newIndex !== -1) {
        const newOrder = arrayMove(gidOrder, oldIndex, newIndex);
        dispatch(setOrder(newOrder));
        dispatch(syncPriorities(newOrder));
      }
    }
  }

  function handleDragCancel() {
    setActiveId(null);
    dispatch(setDragging(false));
  }

  const totalItems = categoryFiltered.length;
  const showEmptyState = !isLoading && totalItems === 0 && !searchQuery && category === 'all';
  const showNoResults = !isLoading && totalItems === 0 && (searchQuery || category !== 'all');

  return (
    <div className="page">
      <header className="toolbar-header">
        <div className="search-bar">
          <span className="material-symbols-outlined">search</span>
          <input
            ref={searchInputRef}
            className="search-input"
            type="text"
            placeholder="Search by filename or paste URL..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          <kbd className="search-shortcut">Ctrl K</kbd>
        </div>
        <div className="toolbar-actions">
          <NotificationDropdown />
          <button className="btn btn-primary" onClick={() => setShowAddModal(true)}>
            <span className="material-symbols-outlined" style={{ fontSize: 20 }}>add</span>
            Add Download
          </button>
        </div>
      </header>

      {hasSelection && (
        <div className="batch-action-bar">
          <label className="select-all-checkbox">
            <input type="checkbox" checked={allSelected} onChange={handleSelectAll} aria-label="Select all downloads" />
          </label>
          <span className="batch-count">{selectedGids.size} selected</span>
          <button className="btn btn-secondary btn-sm" onClick={handleBatchPause}>
            <span className="material-symbols-outlined" style={{ fontSize: 14 }}>pause</span> Pause
          </button>
          <button className="btn btn-secondary btn-sm" onClick={handleBatchResume}>
            <span className="material-symbols-outlined" style={{ fontSize: 14 }}>play_arrow</span> Resume
          </button>
          <button className="btn btn-destructive btn-sm" onClick={handleBatchRemove}>
            <span className="material-symbols-outlined" style={{ fontSize: 14 }}>delete</span> Remove
          </button>
          <button className="btn btn-ghost btn-sm" onClick={() => setSelectedGids(new Set())}>Clear</button>
        </div>
      )}

      {error && (
        <div className="error-banner">
          <span className="material-symbols-outlined" style={{ fontSize: 14 }}>error</span>
          <span>{error}</span>
          <button className="btn btn-ghost btn-sm" onClick={() => dispatch(fetchDownloads())}>Retry</button>
        </div>
      )}

      <div className="content-scroll">
        {/* Category pills */}
        <div className="category-pills">
          {CATEGORIES.map(cat => (
            <button
              key={cat.value}
              className={`category-pill${category === cat.value ? ' active' : ''}`}
              onClick={() => setCategory(cat.value)}
            >
              {cat.label}
            </button>
          ))}
        </div>

        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDragCancel={handleDragCancel}
        >
          {isLoading && totalItems === 0 && !searchQuery ? (
            <div className="empty-state">
              <span className="material-symbols-outlined spin" style={{ fontSize: 32 }}>progress_activity</span>
              <p>Loading downloads...</p>
            </div>
          ) : showEmptyState ? (
            <div className="empty-state">
              <div className="empty-icon">
                <span className="material-symbols-outlined" style={{ fontSize: 48 }}>inbox</span>
              </div>
              <h3>No downloads</h3>
              <p>Click &quot;Add Download&quot; or press Ctrl+N to get started</p>
              <button className="btn btn-primary" onClick={() => setShowAddModal(true)} style={{ marginTop: 'var(--space-md)' }}>
                <span className="material-symbols-outlined" style={{ fontSize: 14 }}>add</span> Add Download
              </button>
            </div>
          ) : showNoResults ? (
            <div className="empty-state">
              <div className="empty-icon">
                <span className="material-symbols-outlined" style={{ fontSize: 48 }}>search_off</span>
              </div>
              <h3>No results</h3>
              <p>Try a different search term or category</p>
            </div>
          ) : (
            <>
              {/* Active Downloads Section */}
              {sortedActiveItems.length > 0 && (
                <div className="download-section">
                  <div className="dl-section-header">
                    <span className="section-dot green" />
                    <span className="section-label">Active Downloads</span>
                  </div>
                  <div className="downloads-list">
                    <SortableContext items={sortedActiveItems.map(d => d.gid)} strategy={verticalListSortingStrategy}>
                      {sortedActiveItems.map(download => (
                        <SortableDownloadCard
                          key={download.gid}
                          download={download}
                          selected={selectedGids.has(download.gid)}
                          onSelect={handleSelect}
                        />
                      ))}
                    </SortableContext>
                    <div className="add-more-zone" onClick={() => setShowAddModal(true)}>
                      <span className="material-symbols-outlined" style={{ fontSize: 16 }}>add</span>
                      <span>Ready for more</span>
                    </div>
                  </div>
                </div>
              )}

              {/* Paused & Recent Section */}
              {pausedCompletedItems.length > 0 && (
                <div className="download-section">
                  <div className="dl-section-header">
                    <span className="section-dot yellow" />
                    <span className="section-label">Paused &amp; Recent</span>
                  </div>
                  <div className="compact-list">
                    {pausedCompletedItems.map(download => (
                      <CompactDownloadRow
                        key={download.gid}
                        download={download}
                        selected={selectedGids.has(download.gid)}
                        onSelect={handleSelect}
                      />
                    ))}
                  </div>
                </div>
              )}

              {/* If only active but no paused, still show add zone */}
              {sortedActiveItems.length === 0 && pausedCompletedItems.length > 0 && (
                <div className="add-more-zone" onClick={() => setShowAddModal(true)}>
                  <span className="material-symbols-outlined" style={{ fontSize: 16 }}>add</span>
                  <span>Ready for more</span>
                </div>
              )}
            </>
          )}

          <DragOverlay>
            {activeDownload ? (
              <div className="drag-overlay-card">
                <div className="sortable-card-wrapper">
                  <div className="drag-handle">
                    <span className="material-symbols-outlined" style={{ fontSize: 16 }}>drag_indicator</span>
                  </div>
                  <DownloadCard download={activeDownload} />
                </div>
              </div>
            ) : null}
          </DragOverlay>
        </DndContext>
      </div>

      {showAddModal && <AddDownloadModal onClose={() => setShowAddModal(false)} />}
    </div>
  );
}
