// src/App.tsx
import React, { useEffect, useCallback, useState } from 'react';
import { Routes, Route, useNavigate } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import Onboarding from './components/Onboarding';
import Sidebar from './components/layout/Sidebar';
import StatusBar from './components/layout/StatusBar';
import Downloads from './pages/Downloads';
import History from './pages/History';
import Settings from './pages/Settings';
import Scheduler from './pages/Scheduler';
import Statistics from './pages/Statistics';
import { updateStats, setDisconnected, selectIsConnected } from './store/statsSlice';
import { setTheme, applySystemTheme } from './store/themeSlice';
import { addDownload, addMagnet, fetchDownloads, restoreIncomplete } from './store/downloadSlice';
import { addNotification } from './store/notificationSlice';
import { setUpdateAvailable, setDownloadProgress, setUpdateDownloaded } from './store/updaterSlice';
import UpdateToast from './components/updater/UpdateToast';
import UpdateModal from './components/updater/UpdateModal';
import type { AppDispatch } from './store/store';
import './App.css';

export default function App() {
  const dispatch = useDispatch<AppDispatch>();
  const navigate = useNavigate();
  const isConnected = useSelector(selectIsConnected);
  const [isDragOver, setIsDragOver] = useState(false);
  const [showOnboarding, setShowOnboarding] = useState(
    () => !localStorage.getItem('gosh-fetch-onboarding-done')
  );

  // Keyboard shortcuts
  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    const mod = e.ctrlKey || e.metaKey;
    if (mod && e.key === 'n') {
      e.preventDefault();
      navigate('/');
      window.dispatchEvent(new CustomEvent('gosh-fetch:open-add-modal'));
    } else if (mod && e.key === 'k') {
      e.preventDefault();
      window.dispatchEvent(new CustomEvent('gosh-fetch:focus-search'));
    } else if (mod && e.key === ',') {
      e.preventDefault();
      navigate('/settings');
    } else if (mod && e.key === 'a' && !['INPUT', 'TEXTAREA'].includes((e.target as HTMLElement)?.tagName)) {
      e.preventDefault();
      window.dispatchEvent(new CustomEvent('gosh-fetch:select-all'));
    }
  }, [navigate]);

  // Drag and drop files/URLs onto window
  function handleDragOver(e: React.DragEvent) {
    e.preventDefault();
    setIsDragOver(true);
  }

  function handleDragLeave(e: React.DragEvent) {
    if (e.currentTarget === e.target || !e.currentTarget.contains(e.relatedTarget as Node)) {
      setIsDragOver(false);
    }
  }

  async function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    setIsDragOver(false);

    // Handle dropped files (.torrent)
    if (e.dataTransfer.files.length > 0) {
      for (const file of Array.from(e.dataTransfer.files)) {
        if (file.name.endsWith('.torrent') && (file as any).path) {
          try {
            await dispatch(addDownload({ url: (file as any).path }));
          } catch { /* ignore */ }
        }
      }
      dispatch(fetchDownloads());
      return;
    }

    // Handle dropped text (URLs, magnet links)
    const text = e.dataTransfer.getData('text/plain')?.trim();
    if (text) {
      const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
      for (const line of lines) {
        try {
          if (line.startsWith('magnet:')) {
            await dispatch(addMagnet({ magnetUri: line }));
          } else if (line.startsWith('http://') || line.startsWith('https://')) {
            await dispatch(addDownload({ url: line }));
          }
        } catch { /* ignore */ }
      }
      dispatch(fetchDownloads());
    }
  }

  useEffect(() => {
    // Initialize theme
    const saved = localStorage.getItem('gosh-fetch-theme') as 'dark' | 'light' | 'system' | null;
    dispatch(setTheme(saved ?? 'dark'));

    // Restore incomplete downloads once on app startup
    dispatch(restoreIncomplete());

    // Listen for events from sidecar via Electron
    const cleanupEvent = window.electronAPI.onEvent((event: string, data: any) => {
      if (event === 'global-stats') {
        dispatch(updateStats(data));
      }
      if (event === 'navigate') {
        navigate(data);
      }
      if (event === 'open-add-modal') {
        window.dispatchEvent(new CustomEvent('gosh-fetch:open-add-modal'));
      }
      if (event === 'native-theme-changed') {
        dispatch(applySystemTheme());
      }
      if (event === 'engine-status') {
        if (!data.connected && !data.restarting) {
          dispatch(setDisconnected());
        }
      }
      // Push-based download list refresh on state changes
      if (event === 'download:added') {
        dispatch(fetchDownloads());
        if (data?.name) {
          dispatch(addNotification({ type: 'added', downloadName: data.name }));
        }
      }
      if (event === 'download:completed') {
        dispatch(fetchDownloads());
        if (data?.name) {
          dispatch(addNotification({ type: 'completed', downloadName: data.name }));
        }
      }
      if (event === 'download:failed') {
        dispatch(fetchDownloads());
        if (data?.name) {
          dispatch(addNotification({ type: 'failed', downloadName: data.name }));
        }
      }
      if (
        event === 'download:removed' ||
        event === 'download:paused' ||
        event === 'download:resumed' ||
        event === 'download:state-changed'
      ) {
        dispatch(fetchDownloads());
      }
      // Auto-updater events
      if (event === 'update-available') {
        dispatch(setUpdateAvailable(data));
      }
      if (event === 'update-progress') {
        dispatch(setDownloadProgress(data));
      }
      if (event === 'update-downloaded') {
        dispatch(setUpdateDownloaded());
      }
    });

    document.addEventListener('keydown', handleKeyDown);

    return () => {
      cleanupEvent();
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [dispatch, navigate, handleKeyDown]);

  return (
    <div
      className="app-layout"
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <Sidebar />
      <div className="main-area">
        <main className="main-content">
          {!isConnected && (
            <div className="connection-banner">
              <span className="material-symbols-outlined" style={{ fontSize: 14 }}>wifi_off</span>
              <span>Engine disconnected</span>
              <span className="material-symbols-outlined spin" style={{ fontSize: 12 }}>sync</span>
              <span>Reconnecting...</span>
            </div>
          )}
          <Routes>
            <Route path="/" element={<Downloads />} />
            <Route path="/history" element={<History />} />
            <Route path="/statistics" element={<Statistics />} />
            <Route path="/settings" element={<Settings />} />
            <Route path="/scheduler" element={<Scheduler />} />
          </Routes>
        </main>
        <StatusBar />
      </div>

      {showOnboarding && <Onboarding onComplete={() => setShowOnboarding(false)} />}

      <UpdateToast />
      <UpdateModal />

      {isDragOver && (
        <div className="drop-overlay">
          <div className="drop-overlay-content">
            <div className="drop-icon">+</div>
            <p>Drop URL or .torrent file to add download</p>
          </div>
        </div>
      )}
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import Router, { push, router } from 'svelte-spa-router';
  import { getCurrentWebview } from '@tauri-apps/api/webview';
  import { getCurrentWindow } from '@tauri-apps/api/window';
  import Downloads from './routes/Downloads.svelte';
  import History from './routes/History.svelte';
  import Statistics from './routes/Statistics.svelte';
  import Settings from './routes/Settings.svelte';
  import Scheduler from './routes/Scheduler.svelte';
  import Mirror from './routes/Mirror.svelte';
  import TrayPopup from './routes/TrayPopup.svelte';
  import Sidebar from './lib/components/layout/Sidebar.svelte';
  import StatusBar from './lib/components/layout/StatusBar.svelte';
  import Onboarding from './lib/components/Onboarding.svelte';
  import UpdateToast from './lib/components/updater/UpdateToast.svelte';
  import UpdateModal from './lib/components/updater/UpdateModal.svelte';
  import { startEventBridge } from './lib/api/events';
  import { downloads } from './lib/stores/downloads.svelte';
  import { stats } from './lib/stores/stats.svelte';
  import { theme } from './lib/stores/theme.svelte';
  import { ui } from './lib/stores/ui.svelte';
  import { updater } from './lib/stores/updater.svelte';
  import './App.css';

  const routes = {
    '/': Downloads,
    '/history': History,
    '/statistics': Statistics,
    '/settings': Settings,
    '/scheduler': Scheduler,
    '/mirror': Mirror,
  };

  // The tray popup window loads the same bundle with #/tray — render it
  // without the app shell.
  let isTrayPopup = $derived(router.location === '/tray');

  let isDragOver = $state(false);
  let showOnboarding = $state(!localStorage.getItem('gosh-fetch-onboarding-done'));

  function handleKeyDown(e: KeyboardEvent) {
    const mod = e.ctrlKey || e.metaKey;
    if (mod && e.key === 'n') {
      e.preventDefault();
      push('/');
      ui.openAddModal();
    } else if (mod && e.key === 'k') {
      e.preventDefault();
      ui.requestFocusSearch();
    } else if (mod && e.key === ',') {
      e.preventDefault();
      push('/settings');
    } else if (
      mod &&
      e.key === 'a' &&
      !['INPUT', 'TEXTAREA'].includes((e.target as HTMLElement)?.tagName)
    ) {
      e.preventDefault();
      ui.requestSelectAll();
    }
  }

  // Text/URL drops come through HTML5 DnD; file drops (.torrent) come
  // through Tauri's native drag-drop events (HTML5 drops carry no paths).
  function handleDragOver(e: DragEvent) {
    e.preventDefault();
    isDragOver = true;
  }

  function handleDragLeave(e: DragEvent) {
    const target = e.currentTarget as HTMLElement;
    if (target === e.target || !target.contains(e.relatedTarget as Node)) {
      isDragOver = false;
    }
  }

  async function handleDrop(e: DragEvent) {
    e.preventDefault();
    isDragOver = false;

    const text = e.dataTransfer?.getData('text/plain')?.trim();
    if (text) {
      const lines = text
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l.length > 0);
      for (const line of lines) {
        try {
          if (line.startsWith('magnet:')) {
            await downloads.addMagnet(line);
          } else if (line.startsWith('http://') || line.startsWith('https://')) {
            await downloads.addDownload(line);
          }
        } catch {
          /* ignore */
        }
      }
      void downloads.fetchDownloads();
    }
  }

  $effect(() => {
    if (isTrayPopup) return;

    // Initialize theme from storage
    theme.setTheme(theme.theme);

    // Restore incomplete downloads once on app startup
    void downloads.restoreIncomplete();
    void downloads.fetchDownloads();
    void downloads.loadCompletedHistory();

    // Check for app updates in the background
    void updater.checkForUpdates();

    let cleanupBridge: (() => void) | null = null;
    let cleanupFileDrop: (() => void) | null = null;

    void startEventBridge().then((cleanup) => {
      cleanupBridge = cleanup;
    });

    // Native file drops (real paths, unlike HTML5 drops in a webview)
    void getCurrentWebview()
      .onDragDropEvent(async (event) => {
        if (event.payload.type === 'over') {
          isDragOver = true;
        } else if (event.payload.type === 'drop') {
          isDragOver = false;
          const torrents = event.payload.paths.filter((p) =>
            p.toLowerCase().endsWith('.torrent')
          );
          for (const filePath of torrents) {
            try {
              await downloads.addTorrentFile(filePath);
            } catch {
              /* ignore */
            }
          }
          if (torrents.length > 0) void downloads.fetchDownloads();
        } else {
          isDragOver = false;
        }
      })
      .then((cleanup) => {
        cleanupFileDrop = cleanup;
      });

    document.addEventListener('keydown', handleKeyDown);

    // The window starts hidden; show it now that the UI is mounted
    void getCurrentWindow().show();

    return () => {
      cleanupBridge?.();
      cleanupFileDrop?.();
      document.removeEventListener('keydown', handleKeyDown);
    };
  });
</script>

{#if isTrayPopup}
  <TrayPopup />
{:else}
  <div
    class="app-layout"
    role="application"
    ondragover={handleDragOver}
    ondragleave={handleDragLeave}
    ondrop={handleDrop}
  >
    <Sidebar />
    <div class="main-area">
      <main class="main-content">
        {#if !stats.isConnected}
          <div class="connection-banner">
            <span class="material-symbols-outlined" style="font-size: 14px">wifi_off</span>
            <span>Engine disconnected</span>
            <span class="material-symbols-outlined spin" style="font-size: 12px">sync</span>
            <span>Reconnecting...</span>
          </div>
        {/if}
        <Router {routes} />
      </main>
      <StatusBar />
    </div>

    {#if showOnboarding}
      <Onboarding onComplete={() => (showOnboarding = false)} />
    {/if}

    <UpdateToast />
    <UpdateModal />

    {#if isDragOver}
      <div class="drop-overlay">
        <div class="drop-overlay-content">
          <div class="drop-icon">+</div>
          <p>Drop URL or .torrent file to add download</p>
        </div>
      </div>
    {/if}
  </div>
{/if}
